spring:
  application:
    name: spring-homework2
  datasource:
    url: jdbc:oracle:thin:@192.168.219.125:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: TODOLIST
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/ktdsuniversity/edu.spring_homework2/**/dao/mapper/*.xml
